/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    Box: typeof import('./src/components/Home/Box/index.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    Func: typeof import('./src/components/Home/Func/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Hitokoto: typeof import('./src/components/Home/Func/Hitokoto.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    Left: typeof import('./src/components/Home/Main/Left.vue')['default']
    Links: typeof import('./src/components/Home/Links.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    LoadingRotateCircle: typeof import('./src/components/Loading/LoadingRotateCircle.vue')['default']
    Message: typeof import('./src/components/Home/Message.vue')['default']
    MoreContent: typeof import('./src/components/MoreContent.vue')['default']
    Right: typeof import('./src/components/Home/Main/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLinks: typeof import('./src/components/Home/SocialLinks.vue')['default']
    TimeCapsule: typeof import('./src/components/Home/Box/TimeCapsule.vue')['default']
    TimeClock: typeof import('./src/components/TimeClock.vue')['default']
    TimeWeather: typeof import('./src/components/Home/TimeWeather.vue')['default']
  }
}
