/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    LoadingRotateCircle: typeof import('./src/components/Loading/LoadingRotateCircle.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MoreContent: typeof import('./src/components/MoreContent.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TimeClock: typeof import('./src/components/TimeClock.vue')['default']
    TimeWeather: typeof import('./src/components/TimeWeather.vue')['default']
  }
}
